### PR TITLE
Make one review for files

### PR DESCRIPTION
**Pull request by keenranger**
Current action populate github PR with a lot of comments when many file changes.

This PR enable action to gather all the comments in one review.

Please review this and build using this file.

### CODE REVIEW

**Comment by tawhidnazari57** [comment]
is:pr is:open

**Review by tawhidnazari57 — APPROVED** [review]

**Comment by drakejin** [comment]
is this PR dead?

**Comment by anc95** [comment]
I missed this one, will test it to ensure it's workable then merge it.

**Comment by anc95** [comment]
works well. merged and released v1.0.15

**Pull request merged**
