### PR TITLE
Bug fix on azure open ai

### PR DESCRIPTION
**Pull request by shkangomelet**
I apologize, but it turns out that my recent commit (https://github.com/anc95/ChatGPT-CodeReview/pull/163) isn’t functioning as expected. Unfortunately, I created it manually without thoroughly testing.

Now, after testing with the following script, I have confirmed it works well:

```typescript
import { OpenAI, AzureOpenAI } from 'openai';

export class Chat {
  private openai: OpenAI | AzureOpenAI;
  private isAzure: boolean;

  constructor(apikey: string) {
    this.isAzure = Boolean(
        process.env.AZURE_API_VERSION && process.env.AZURE_DEPLOYMENT,
    );

    if (this.isAzure) {
      // Azure OpenAI configuration
      this.openai = new AzureOpenAI({
        apiKey: apikey,
        endpoint: process.env.OPENAI_API_ENDPOINT || '',
        apiVersion: process.env.AZURE_API_VERSION || '',
        deployment: process.env.AZURE_DEPLOYMENT || '',
      });
    } else {
      // Standard OpenAI configuration
      this.openai = new OpenAI({
        apiKey: apikey,
        baseURL: process.env.OPENAI_API_ENDPOINT || 'https://api.openai.com/v1',
      });
    }
  }

  private generatePrompt = (patch: string) => {
    const answerLanguage = process.env.LANGUAGE
        ? `Answer me in ${process.env.LANGUAGE},`
        : '';

    const prompt =
        process.env.PROMPT ||
        'Below is a code patch, please help me do a brief code review on it. Any bug risks and/or improvement suggestions are welcome:';

    return `${prompt}, ${answerLanguage}:
  ${patch}
    `;
  };

  public codeReview = async (patch: string) => {
    if (!patch) {
      return '';
    }

    console.time('code-review cost');
    const prompt = this.generatePrompt(patch);

    const res = await this.openai.chat.completions.create({
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      model: process.env.MODEL || 'gpt-4o-mini',
      temperature: +(process.env.temperature || 0) || 1,
      top_p: +(process.env.top_p || 0) || 1,
      max_tokens: process.env.max_tokens ? +process.env.max_tokens : undefined,
    });

    console.timeEnd('code-review cost');

    if (res.choices.length) {
      return res.choices[0].message.content;
    }

    return '';
  };
}

// Test code to run codeReview directly
async function testCodeReview() {
  const apiKey = process.env.OPENAI_API_KEY || '';
  const chat = new Chat(apiKey);

  // Sample code patch for review
  const patch = `
  function add(a, b) {
    return a + b;
  }
  `;

  try {
    const review = await chat.codeReview(patch);
    console.log('Code Review Output:', review);
  } catch (error) {
    console.error('Error in codeReview:', error);
  }
}

// Run the test
testCodeReview();

```

I’ve tested the script using the following two configurations, and it performed as expected:

```bash
export OPENAI_API_KEY="azure_api_key"                 
export OPENAI_API_ENDPOINT="https://omelet-openai-us.openai.azure.com"
export AZURE_API_VERSION="2024-08-01-preview"
export AZURE_DEPLOYMENT="gpt-4o-2"
export MODEL="gpt-4o"
```

```bash
export OPENAI_API_KEY="openai_api_key"                 
export OPENAI_API_ENDPOINT=""
export AZURE_API_VERSION=""
export AZURE_DEPLOYMENT=""
export MODEL="gpt-4o"
```

reference: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai/README.md

### CODE REVIEW

**Comment by shkangomelet** [comment]
image
image
I added two test result

**Comment by anc95** [comment]
@shkangomelet could you run `npm run build` locally and then commit and push the update.

**Comment by shkangomelet** [comment]
@anc95 I did it!

**Comment by anc95** [comment]
released. Thank you 👍

**Pull request merged**
